language: csharp

solution: src/csharp-kit.sln

env:
 matrix:
  - MONO_VERSION="3.8.0"

install:
  - nuget restore src/csharp-kit.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release src/csharp-kit.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe src/prismic.tests/bin/Release/prismic.tests.dll
